spring.application.name=NoteKeep
#spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.database=NoteKeep
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email 
                                                        #scope of request
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
                                                                            #code to get token from google. 
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId} 
                                                                #change baseUrl with your own website.
spring.security.oauth2.client.registration.google.client-name=Google

# Set false to disable the OCR endpoint temporarily.
notekeep.ocr.enabled=false
