spring.application.name=NoteKeep
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/NoteKeep}

spring.data.mongodb.database=NoteKeep

# Set false to disable the OCR endpoint temporarily.
#1notekeep.ocr.enabled=false
spring.cloud.gcp.parametermanager.enabled=false  
