apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-metadata-name-notekeep
  namespace: common-metadata-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      service: deployment-notekeep-template-metadata-label-service # select the temple from below
  template:
    metadata:
      labels:
        service: deployment-notekeep-template-metadata-label-service
    spec:
      containers:
      - image: ghcr.io/fethullahcucu/notekeep:main # change later
        imagePullPolicy: Always
        name: api  # change later
        ports:
          - containerPort: 8000
        env:
          - name: MONGODB_URI
            value: mongodb://service-metada-name-mongodb.mongodb.svc.cluster.local:27017/NoteKeep
          - name: DATABASE_HOST
            value: service-metada-name-mongodb.mongodb.svc.cluster.local
          - name: DATABASE_PORT
            value: "27017"
