name : Run tests
on:
  pull_request:
    branches:
        - main
  push:
    branches:
        - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v5
        with: 
          java-version: '17'
          distribution: 'temurin'
          
      - name: Write GCP credentials to file
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > ${{ github.workspace }}/gcp-key.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV



      - name: run test
        run: |
          echo "Secret value is $MY_SECRET"
          chmod +x mvnw
          ./mvnw test


