name : Run tests
on:
  pull_request: # Trigger when someone opens a pull request
    branches:
        - main # Targeting the 'main' branch
  push: # Trigger when someone pushes commits
    branches:
        - main # To the 'main' branch
jobs: # here is what actions will do
  test: # Define the test job
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps: # steps list
      - name: Checkout code # Mame of the step
        uses: actions/checkout@v4 # Fetch the latest code from the repository

      - name: set up java
        uses: actions/setup-java@v5 # Set up the Java environment
        with: 
          java-version: '17' # Specify the Java version
          distribution: 'temurin' # Use the Temurin JDK distribution
      - name: Prepare GCP credentials
        env: #if you want to set env 
          MONGODB_URI : mongodb://localhost:27017/NoteKeep
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }} # Load the GCP service account key from GitHub Secrets
          GOOGLE_CLIENT_ID: ${{env.GOOGLE_CLIENT_SECRET}}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: | # Write the service account key to a temporary JSON file and Set the environment variable for authentication
          printf '%s' "$GCP_SERVICE_ACCOUNT_JSON" > "$RUNNER_TEMP/gcloud.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcloud.json" >> "$GITHUB_ENV"
          
      - name: run test
        run: | # Grant execute permission to the Maven wrapper. Run the Maven test command
          chmod +x mvnw 
          ./mvnw test
  push_new_image:
    runs-on: ubuntu-latest #Use the latest Ubuntu runner 
    needs: 
      - test # make sure this job is done before move on
    if: github.ref == 'refs/heads/main' #if you are at main branch,
    permissions: # give permissions below
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps: #follow steps below.
      - name: Checkout code # Mame of the step
        uses: actions/checkout@v4 # Fetch the latest code from the repository
      
      - name: Login to GHCR
        uses: docker/login-action@v3 #login to docker
        env:
          GHCR_REGISTRY: ${{ vars.GHCR_REGISTRY }}
        with:
          registry: ${{env.GHCR_REGISTRY}} # with ghcr.io (from repo env)
          username: ${{ github.actor }} # username of who push the workflow
          password: ${{ secrets.GITHUB_TOKEN }} # temporary token by github to login.
      - name: Docker meta 
        id: meta
        uses: docker/metadata-action@v5 ##which auto-generates image tags and OCI labels based on the Git ref (branch, tag), commit SHA, PR number, etc.
        with:
          images: ghcr.io/fethullahcucu/notekeep #Declares the base image name to tag. The action will produce outputs like:
                                                 #tags (e.g., ghcr.io/fethullahcucu/notekeep:sha-<shortsha>, :main, :v1.2.3, depending on event/inputs)
                                                 #labels (standard org.opencontainers.image.* labels)
      - name: Build jar # build a jar without test 
        run: |
          chmod +x mvnw
          ./mvnw -DskipTests package 
      - name: Build and push
        uses: docker/build-push-action@v6 
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 


#test
